### ISSUE TITLE
change endl to newline

### ISSUE THREAD

**Issue by cppxor2arr** [feddischson/include_gardener#10]
`std::endl` flushes the buffer which is relatively slow; should `std::endl` be changed to `'\n'`?

**Comment by feddischson** [comment]
Hi,

could you provide me a short example of how you are using the tool (the command with the arguments)?

... Just to be sure, that I understand your improvement request correctly.

Cheers

**Comment by LesnyRumcajs** [comment]
I replaced std::endl with '\n', compared the performance. 

```
(std::endl)
time for i in {1..100}; do include_gardener -P src/ -o graph.dot; done

real	1m7.859s
user	2m10.908s
sys	0m3.544s
```

```
('\n')
time for i in {1..100}; do include_gardener -P src/ -o graph.dot; done

real	1m7.754s
user	2m10.184s
sys	0m3.660s
```
I get consistently better results, though they're really small.

**Comment by feddischson** [comment]
@LesnyRumcajs Thanks for your improvements. 
The reason, why there is just a small difference is because there are just a few lines printed now with `\n`.


I guess @cppxor2arr intended to replace also `std::end`l of the logging output, which is activated via `-V`, right?
The logging is also used for debugging and sometimes it is sometimes useful to have a `std::endl` instead of a `\n`.
In which situation or use-case did you encounter the slow buffer flushes? Could you provide an example for us?

**Comment by LesnyRumcajs** [comment]
Buffer flushes weren't slow in this particular case. However, the use of std::endl is now rather discouraged - an example talk from CppCon 2017 https://www.youtube.com/watch?v=6WeEMlmrfOI.
