### ISSUE TITLE
Python Realization

### ISSUE THREAD

**Issue by feddischson** [feddischson/include_gardener#16]
One of the goal with v1.0.0 was to re-write the architecture to enable multiple languages.

For this reason, it would be interesting to write a `Solver_Py` class, derived from the `Solver` class, which enables the detection of Python import statements in Python code.

Please leave a comment if somebody is interested in writing this extension.

**Comment by Chippyri** [comment]
Hello!
I'm a student on my third year studying software engineering. In the course _Applied Computer Engineering_ we are required to find an open source project to make a meaningful contribution to in pairs.

I would like to express my interest in working with on this issue. I've started setting up the development enviroment for the project and reading a bit about how it functions. Later this week I will post if I am fully committed to this issue after having some time getting acquainted with the code.

I see that there are two branches here, master and multi_language. It seems that multi_language has been merged with master some time ago, so should I clone the master branch if I would be working on this extension?

Thank you for your time.

**Comment by feddischson** [comment]
Hi,

thanks for your comment.

Yes, please clone the master branch to do this extension.
There are three points which could be done:
 - Extension of the C++ Code
 - Testing the extension by unit tests (see `test/unit_test`)
 - Testing the extension by command-line tests (see `tests/cmd_line`)

Just let me know if you have more questions.

**Comment by Chippyri** [comment]
Thanks!

I have been looking around the code and find it relatively easy/familiar to understand. I will see with my potential work partner, but I believe I am committed to this issue. I/we will be forking the project around the time when we will begin implementation.

Currently we are in a project proposal period in our course, but after that (_assuming the project proposal is accepted!_) we can begin with requirements gathering which is estimated to take 2 weeks. This might also be a time where we may ask some further questions regarding the requirements. Implementation with tests will happen after that. Finally, when we are done, we may create a pull request here.

So it may take a while before a result appears, but this is strictly decided by the course plan. I hope that this is okay with everyone!

**Comment by feddischson** [comment]
That sounds good for me.

Just have a look here https://docs.python.org/3/reference/import.html if you have  not already seen it.

I also created an overview (which might be not 100 % complete) here somewhen last year: 
https://github.com/feddischson/include_gardener/blob/master/doc/lang/python.md

Feel free to extend this overview. Its good to fully understand the Python import system before planning the realization.

Please don't consider dynamically importing a module by name as explained here: https://github.com/feddischson/include_gardener/blob/master/doc/lang/python.md
Such an approach goes behind the goal of this tool.

**Comment by Chippyri** [comment]
The project proposal has been accepted in part, but I will have to make some final additions to it before work can start.

You've brought up good points. I hope I/we can contribute to the Python overview during our requirements gathering next week, while simultaneously learning how it works. It is also good that you have narrowed down that dynamic importing is not a requirement.

Thank you for your patience and I hope you will hear more from me/us during the following weeks!

**Comment by Chippyri** [comment]
Hello again!
During our requirements gathering we didn't manage to rewrite the Python Overview, but now we have a better understanding of how the imports work. We have added the update to the Python Overview as a non-functional requirement along with code conformity with the project, output consistent with the C/C++ solver, unit tests, dummy test files and documentation formatted for Doxygen.

These are the functional requirements we have planned to implement in the extension.

**High priority:**

* Handling of absolute Python imports.
* Handling of package imports of modules.
* Imports in `__path__`-files.
* That the resulting graph will show correct relationships between **files**.
* Imports can be anywhere in a file or protected with conditional statements and they will still be picked up in the graph.

**Low priority, will be implemented if we have the time:**

* Handling of relative Python imports ex. `from .. import module`.
* If an imported module is bound with another name, it is displayed with a "as boundname" label in next to the node or edge in the graph. (If possible!)
* Imports on the form `from package import *`, respecting the `__all__` in `__path__`-files.

**What we will most likely not implement:**

* Handling of dynamic imports.
* Nodes in graph for specific functions/classes/variables.
* Nodes in graph for files outside of the path supplied to Include Gardener (ex. Python looks in PYTHONPATH). These will however end up as leaf nodes in our planned implementation, they're just not "followed up" for discovering more imports. 

Some of the functionality mentioned here is already present in Include Gardener and how the program functions. We thought however it would be important to make clear how we expect the extension to function in conjunction with the rest of the program. 

Now, we made the mistake of sending in our requirements gathering before consulting with you (sorry!), but any feedback on our plans if any are very welcome! 😄

**Comment by feddischson** [comment]
No problem, the requirements are fine. 

Just one point: 
The syntax like
```
from foo import bar
```
are common use cases.
It is even possible to do something like
```
from foo import bar as b
from foo import aa as a, bb as
```
It would be good to consider this also as High Priority.

**Comment by Chippyri** [comment]
Yes, you are right. We will add this as another functional requirement. Thank you.

**Comment by Chippyri** [comment]
```
vector<regex> Statement_Detector::get_statements() const { return statements; }

optional<pair<string, unsigned int>> Statement_Detector::detect(
    const string& line) const {
  smatch match;
  for (unsigned int i = 0; i < statements.size(); i++) {
    auto s = statements[i];
    if (regex_search(line, match, s)) {
      if (!match.empty()) {
        BOOST_LOG_TRIVIAL(trace) << "Statement matched: " << match[match.size() - 1];
        return pair<string, unsigned int>(match[match.size() - 1], i);
      }
    }
  }
  return {};
}
```

Am I correct in my understanding that detect() in Statement_Detector only returns a single Pair<string, unsigned int> with the first match that was made, the rest are ignored for the line? So a Python import regex which contains multiple matching groups will probably not function as expected as only the ```match[match.size() - 1]``` at the last index is returned if one of the (regex) statements doesn't turn up empty.

Do you think this may warrant modification of Statement_Detector? Instead of returning a single string in the pair, it could return all matches in a vector?

**Comment by feddischson** [comment]
Yes that should no be a problem. The solver_c is using a no capturing group `(?:include|import)` within the regex, so it should be possible to make the change without breaking the solver_c functionality.

**Comment by Chippyri** [comment]
Hello! I wanted to give an update regarding the Python extension. The course has now concluded but the implementation is not fully working as it should yet, so I am hesitant in sending a Pull Request at this state.

We decided against modifying the rest of the program and instead concentrated the string parsing and splitting to Solver_Py, so that no future extensions that may have been created concurrently would have broken. _(The string functions would probably fit better in some helper class in case other extensions would require them.)_ Getting most of the import string also preserved some context for the import. We took the approach that Python import statements can be implicitly translated to paths.

The biggest problem lies in how the Solver_Py currently evaluates absolute imports. My (sadly, wrong) interpretation was that absolute imports also functioned in a relative way, but instead they are actually always resolved from the project root! 

Furthermore, no options have been implemented yet. I was thinking that the given path should be the project root and that this could be given as an option to the solver so that it knows where to look for absolute imports.

I will continue working on this on my spare time, but if you are curious in testing how it currently works, it is available on the development branch here: https://github.com/dt002g-team-6/include_gardener/tree/development Use flag ```-l py```. Any constructive criticism is welcome, otherwise please wait for the Pull Request.

I will be making a fork of this fork to preserve the group work's current state in case the teachers are interested in having this group project "snapshot" as is.

Thank you for your patience once again.
